name: Perlcritic check

on:
  pull_request:
    types: [opened, synchronize]


jobs:
  critic:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
      issues: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1.12.3
      with:
        perl-version: 5.32
        install-modules-with: cpanm
        install-modules: Perl::Critic Task::PerlCriticAllPolicies 
        install-modules-args: --notest
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
    - name: run perlcritic and send report via reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        perlcritic --verbose 1 --profile .perlcritic ./FHEM | \
            reviewdog -efm '%f:%l:%c:%m' \
            -diff="git diff ${{github.head_ref}}..${{ github.base_ref}}" \
            -name="perlcritic" \
            -reporter="github-pr-review" \
            -filter-mode="diff_context" \
            -fail-on-error="false" \
            -level="warning" \
